{
 "title": "Internet/Netflow/Bird",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(bird_protocol_up,instance)"
    }
   },
   {
    "name": "as",
    "label": "Netflow ASN",
    "query": {
     "query": "label_values(flow_transmit_bytes_total,destination_as)"
    }
   },
   {
    "name": "netflow_host",
    "label": "Host (netflow)",
    "query": {
     "query": "label_values(flow_receive_bytes_total,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bird Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{unit=\"bird.service\", host=\"$netflow_host\"} |= ``"
    }
   ]
  },
  { "title": "Bird2 exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bird Prefix Import Count IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_import_count{instance=\"$host\",ip_version=\"4\",proto=\"BGP\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Bird Prefix export Count IPv4",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_export_count{instance=\"$host\",ip_version=\"4\",proto=\"BGP\",name!=\"pmacctd\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "peerings up",
   "type": "stat",
   "gridPos": { "h": 21, "w": 14, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_protocol_up{instance=\"$host\",ip_version=\"4\",proto=\"BGP\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bird Prefix Import Count IPv6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_import_count{instance=\"$host\",ip_version=\"6\",proto=\"BGP\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Bird Prefix export Count IPv6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_export_count{instance=\"$host\",ip_version=\"6\",proto=\"BGP\",name!=\"pmacctd\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Preferred routes IPv4 (BGP)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_preferred_count{instance=\"$host\",ip_version=\"4\",proto=\"BGP\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Preferred routes IPv6 (BGP)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_preferred_count{instance=\"$host\",ip_version=\"6\",proto=\"BGP\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  { "title": "Netflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Inbound Traffic by IP by source_net",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_receive_bytes_total_by_net{hostname=~\"$netflow_host\"}[1m]) * 8) by (source_net))",
     "legendFormat": "{{source_net}}"
    }
   ]
  },
  {
   "title": "top 15 source subnets",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 20, "w": 14, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "topk(15, sum(rate(flow_receive_bytes_total_by_net{hostname=~\"$netflow_host\"}[1m]) * 8) by (destination_net, source_net))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Traffic by IP by destination_net",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_transmit_bytes_total_by_net{hostname=~\"$netflow_host\"}[1m]) * 8) by (destination_net))",
     "legendFormat": "{{destination_net}}"
    }
   ]
  },
  {
   "title": "Inbound Traffic by IP by destination_net",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_receive_bytes_total_by_net{hostname=~\"$netflow_host\"}[1m]) * 8) by (destination_net))",
     "legendFormat": "{{destination_net}}"
    }
   ]
  },
  {
   "title": "Outbound Traffic by IP by source_net",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_transmit_bytes_total_by_net{hostname=~\"$netflow_host\"}[1m]) * 8) by (source_net))",
     "legendFormat": "{{source_net}}"
    }
   ]
  },
  {
   "title": "Inbound Traffic by AS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_receive_bytes_total{source_as=~\"$as\",hostname=~\"$netflow_host\"}[1m]) * 8) by (source_as, source_as_name))",
     "legendFormat": "{{source_as_name}} (AS{{source_as}})"
    }
   ]
  },
  {
   "title": "top 15 source ASNs",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 19, "w": 14, "x": 5, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "topk(15, sum(rate(flow_receive_bytes_total{hostname=~\"$netflow_host\"}[1m]) * 8) by (source_as, destination_as))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Traffic by AS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_transmit_bytes_total{destination_as=~\"$as\",hostname=~\"$netflow_host\"}[1m]) * 8) by (destination_as, destination_as_name))",
     "legendFormat": "{{destination_as_name}} (AS{{destination_as}})"
    }
   ]
  },
  {
   "title": "Top Inbound ASNs",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_receive_bytes_total{source_as=~\"$as\",hostname=~\"$netflow_host\"}[$__range]) * 8) by (source_as, source_as_name))",
     "legendFormat": "{{source_as}}"
    }
   ]
  },
  {
   "title": "Top Outbound ASNs",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 52 },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_transmit_bytes_total{destination_as=~\"$as\",hostname=~\"$netflow_host\"}[$__range]) * 8) by (destination_as, destination_as_name))"
    }
   ]
  },
  {
   "title": "Inbound Traffic by AS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_receive_bytes_total_by_port{source_as=~\"$as\",hostname=~\"$netflow_host\"}[1m]) * 8) by (destination_port))",
     "legendFormat": "{{destination_port}}"
    }
   ]
  },
  {
   "title": "top 15 destination ASNs ",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 19, "w": 14, "x": 5, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "topk(15, sum(rate(flow_transmit_bytes_total{hostname=~\"$netflow_host\"}[1m]) * 8) by (source_as,destination_as))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Traffic by Port",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_transmit_bytes_total_by_port{destination_as=~\"$as\",hostname=~\"$netflow_host\"}[1m]) * 8) by (destination_port))",
     "legendFormat": "{{destination_port}}"
    }
   ]
  },
  {
   "title": "Top Inbound Ports",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_receive_bytes_total_by_port{source_as=~\"$as\",hostname=~\"$netflow_host\"}[$__range]) * 8) by (destination_port))"
    }
   ]
  },
  {
   "title": "Top Outbound Ports",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 71 },
   "targets": [
    {
     "expr": "topk(100, sum(rate(flow_transmit_bytes_total_by_port{destination_as=~\"$as\",hostname=~\"$netflow_host\"}[$__range]) * 8) by (destination_port))"
    }
   ]
  }
 ]
}