{
  pkgs,
  pkgs-unstable,
  ...
}:
{
  environment.systemPackages =
    (with pkgs; [
      ansible
      tmux
      vim
      fastfetch
      zsh
      nmap
      git
      btop
      wget
      rclone
      restic
      gtop
      freerdp
      killall
      picocom
      gnumake
      curl
      dig
      wireguard-tools
      colmena
      stats
      git-lfs
      openssl
      pwgen
      uv
      jq
      yq
      firefox
      google-chrome
      openvpn
      # bitwarden-desktop
      dash
      #spotify
      nil
      nixd
      python314
      gh
      #pre-commit
      docker
      docker-compose
      colima
      metasploit
      postgresql_18
      mitmproxy
      wireshark
      devenv
      zotero
      androidenv.androidPkgs.ndk-bundle
      cargo-ndk
      rustc
      rustup
    ])
    ++ (with pkgs-unstable; [
      # caffeine on stable does not support aarch64-darwin
      caffeine
      direnv
      #istat-menus
      github-copilot-cli
      mpv-unwrapped
    ]);
}
