{
  pkgs,
  pkgs-unstable,
  ...
}:
{
  environment.systemPackages =
    (with pkgs; [
      ansible
      tmux
      vim
      neofetch
      zsh
      nmap
      git
      btop
      wget
      rclone
      restic
      gtop
      freerdp
      killall
      picocom
      gnumake
      curl
      dig
      wireguard-tools
      colmena
      stats
      git-lfs
      openssl
      pwgen
      php
      ddev
      uv
      jq
      yq
      firefox
      google-chrome
      jetbrains.phpstorm
      openvpn
      bitwarden-desktop
      istat-menus
      dash
      spotify
      nil
      nixd
      bitwarden-cli
      python314
      gh
      pre-commit
      docker
      docker-compose
      colima
      vagrant
      dbeaver-bin
      zerotierone
      metasploit
      postgresql_18
      mitmproxy
      wireshark
      jellyfin-mpv-shim
    ])
    ++ (with pkgs-unstable; [
      # caffeine on stable does not support aarch64-darwin
      caffeine
      direnv
      mpv-unwrapped
    ]);
}
