{
 "title": "Tor Relays_dev",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Traffic receive last week",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{job=\"tor\"}[1w]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic transmit last week",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=\"tor\"}[1w]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Traffic in the last week (both ways)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{job=\"tor\"}[1w])) + sum(increase(node_network_transmit_bytes_total{job=\"tor\"}[1w]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=\"tor\"}[1d])) + sum(increase(node_network_receive_bytes_total{job=\"tor\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic currently (Reseive)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"tor\"}[$__rate_interval])) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"tor\"}[$__rate_interval])) * 8 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"tor\"}[$__rate_interval])) * 8 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic currently (transmit)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"tor\"}[$__rate_interval])) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Onion Skins",
   "type": "timeseries",
   "description": "Onion Skins per second for last 1 hour",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(tor_relay_load_onionskins_total[5m])",
     "legendFormat": "{{type}} {{action}}"
    }
   ]
  },
  {
   "title": "Opened Sokets",
   "type": "stat",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "tor_relay_circuits_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Traffic currently (Reseive)",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=\"tor\" }[$__rate_interval])) without (device, job)*8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}